name: FPL Data Sync

on:
  schedule:
    # Run every 15 minutes during FPL season
    - cron: '*/15 * * * *'
  workflow_dispatch: # Allow manual trigger
  push:
    branches: [main]
    paths: ['participants.config.js']

jobs:
  sync-fpl-data:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        
    - name: Install dependencies
      run: npm install
        
    - name: Fetch FPL bootstrap data
      run: |
        node -e "
        const https = require('https');
        const fs = require('fs');
        
        const fetchData = (url) => {
          return new Promise((resolve, reject) => {
            https.get(url, (res) => {
              let data = '';
              res.on('data', chunk => data += chunk);
              res.on('end', () => {
                try {
                  const json = JSON.parse(data);
                  resolve(json);
                } catch (e) {
                  reject(e);
                }
              });
            }).on('error', reject);
          });
        };
        
        const fetchEntryHistory = async (entryId) => {
          try {
            const data = await fetchData(\`https://fantasy.premierleague.com/api/entry/\${entryId}/history/\`);
            return data;
          } catch (e) {
            console.error(\`Failed to fetch history for \${entryId}:\`, e.message);
            return null;
          }
        };
        
        const main = async () => {
          try {
            // Fetch bootstrap data
            console.log('Fetching bootstrap data...');
            const bootstrap = await fetchData('https://fantasy.premierleague.com/api/bootstrap-static/');
            
            // Ensure data directory exists
            if (!fs.existsSync('data')) {
              fs.mkdirSync('data');
            }
            
            // Save bootstrap data
            fs.writeFileSync('data/bootstrap-static.json', JSON.stringify(bootstrap, null, 2));
            console.log('Bootstrap data saved');
            
            // Get entry IDs from config
            const config = require('./participants.config.js');
            const entryIds = config.ENTRY_IDS || [];
            
            if (entryIds.length > 0) {
              console.log(\`Fetching history for \${entryIds.length} entries...\`);
              
              // Fetch history for each entry (with concurrency limit)
              const concurrency = 3;
              const results = {};
              
              for (let i = 0; i < entryIds.length; i += concurrency) {
                const batch = entryIds.slice(i, i + concurrency);
                const promises = batch.map(async (entryId) => {
                  const history = await fetchEntryHistory(entryId);
                  if (history) {
                    results[entryId] = history;
                  }
                  // Rate limiting
                  await new Promise(resolve => setTimeout(resolve, 200));
                });
                
                await Promise.all(promises);
                console.log(\`Processed batch \${Math.floor(i/concurrency) + 1}\`);
              }
              
              // Save all history data
              fs.writeFileSync('data/entry-histories.json', JSON.stringify(results, null, 2));
              console.log(\`History data saved for \${Object.keys(results).length} entries\`);
            }
            
            // Create a summary file
            const summary = {
              timestamp: new Date().toISOString(),
              bootstrap: {
                events: bootstrap.events?.length || 0,
                teams: bootstrap.teams?.length || 0,
                players: bootstrap.elements?.length || 0
              },
              entries: Object.keys(results).length,
              latestEvent: bootstrap.events?.find(e => e.finished)?.id || 'unknown'
            };
            
            fs.writeFileSync('data/summary.json', JSON.stringify(summary, null, 2));
            console.log('Summary saved:', summary);
            
          } catch (e) {
            console.error('Failed to sync FPL data:', e);
            process.exit(1);
          }
        };
        
        main();
        "
        
    - name: Commit and push data
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add data/
        git diff --quiet && git diff --staged --quiet || git commit -m "Sync FPL data [skip ci]"
        git push
        
    - name: Update data timestamp
      run: |
        echo "Last updated: $(date -u +'%Y-%m-%d %H:%M:%S UTC')" > data/last-updated.txt
        git add data/last-updated.txt
        git commit -m "Update data timestamp [skip ci]" || echo "No changes to timestamp"
        git push
